### ISSUE TITLE
Documentation request: compat/json_style.ts

### ISSUE THREAD

**Issue by photomattmills** [protomaps/protomaps.js#29]
Really I'd just like to know what the expected JSON shape for this is, if any. I was thinking about building something like this for Mapbox Studio/Maputnik JSON output files, so those styles could be used in conjunction with protomaps rendering. Is that the direction this is heading?

**Comment by bdon** [comment]
https://github.com/protomaps/protomaps.js/blob/master/examples/json_style.html is all that exists right now; the first argument is a JSON object that can be also be read by Mapbox GL, MapLibre GL, OpenLayers, etc, although the only key used is the "Layers" key. The result then has a paint_rules and label_rules that can be passed to leafletLayer. 

It's not too elegant right now, but yes, the idea is to read the same style specification used by other map renderers. The difficulty here is that the spec surface area as defined by Mapbox or MapLibre is huge; right now only a limited set is implemented. The rendered result will also look difference because the underlying algorithms and rasterization are fundamentally different. 

So my plan is not to promise a 1:1 match between other JSON styles and the rendering output of protomaps.js, but have something where you can reasonable write one "style" and use it both in MapLibre GL, protomaps.js, with an editor like [Maputnik](http://maputnik.github.io) or [Fresco](http://fresco.go-spatial.org), etc. I've started to explore this universal themes idea [here](https://github.com/protomaps/protomaps-themes/tree/master/base).

**Comment by photomattmills** [comment]
I think that's what I'm after as well; although currently using a style output from Mapbox's style editor (I haven't tried Maputnik yet but it's on the docket) results in nothing but water being rendered. I think this could be because the Mapbox v8 tiles I'm using don't conform to the standard they set, though; or it could be as you say, the style standard is huge and most of it is un-implemented. I'm actively working in this area, once I have something to show I'll open a PR, if that's cool? Probably a bit larger than the last one.

**Comment by bdon** [comment]
If you are using the Mapbox style editor with the Mapbox API, it's likely that the way map features are tagged and organized into layers is disjoint from how they appear in the Protomaps tiles, though they may be built from the same underlying OpenStreetMap data; documentation on how these are organized is online here: https://protomaps.com/docs/map-layers-tags

Though it might be the case certain layers like "water" happen to be similar.

**Comment by photomattmills** [comment]
Yeah, that's what I meant. Sorry, I think of file structures/tagging/organization as asynchronous APIs. Thanks for all the info!
