### ISSUE TITLE
Feature Request: Dynamically set new paint rules

### ISSUE THREAD

**Issue by cduruk** [protomaps/protomaps.js#31]
One thing we are exploring is dynamically updating the paint rules for a given layer. Our higher level goal is to enable some sort of interactivity. Imagine we get some object's properties, and then update our paint rules to special-case that object, and then re-render the tiles.

I sort of hacked it together and it seems to work but wanted to check if my implementation is right. Basically, I added a new public method to `LeafetlLayer` that takes in a new `paintRules` array similar to how it's normally passed in.

Happy to send a PR.

**Comment by bdon** [comment]
Something like this should work:

```
layer.paint_rules = paint_rules
layer.rerenderTiles()
```

I haven't put a lot of thought into this API, so I'm open to suggestions. Implementing a `setPaintRules` method that effectively does the two above might be a little cleaner. LabelRules are different, since the internal label collision state is retained (`Labeler`); there is an existing method called `clearLayout` for that.

Taking a step back, I am skeptical that enabling this kind of interactivity belongs in leafletLayer, because it may be better implemented as a plain Leaflet layer on top of the basemap using SVG shape primitives, where hit-detection is built in, instead of reinventing the wheel.

It *might* make sense if the objects you're interacting with lie in vector tiles already, but I would check that the performance is acceptable in all cases like 4K resolutions or older devices, since the immediate-mode technique protomaps.js uses is going to be UI-blocking and slower than a retained-mode system like MapboxGL/MaplibreGL.
