### ISSUE TITLE
Allow TextSymbolizer that ignores placement of other data, which scales up and down with zoom

### ISSUE THREAD

**Issue by tarngerine** [protomaps/protomaps.js#42]
In discussion with brandon, couple of thoughts here

- we'd like to inject our own user-created annotations into the rendered basemap
- we would like these annotations (E.g. a text layer) to not be automatically hidden like typical map features/labels are — like figma, users should be able to place annotations wherever they want and handle overlaps themselves
- api might look something like, in `styles.ts`:

```
  {
    dataLayer: `annotation_label`,
    symbolizer: new CenteredTextSymbolizer({
      fill: params.annotationLabel,
      align: 'center',
      font: (z, p) => `...`, // dynamically sizes down/up based on some custom logic
      ignorePlacement: true,
    }),
}
```

**Comment by bdon** [comment]
> users should be able to place annotations wherever they want and handle overlaps themselves

This seems like something that should be handled by the DOM instead of Canvas, otherwise we would need a way to to do 60fps animation inside of Canvas; the current design is only to do draw calls at panning or zooming events and not in response to mouse events. 

Could you imagine how this might work as a different canvas layer separate from the base layer? We would need to expose some hooks for matching the coordinate reference systems, as well as edge cases like - what happens if the user zooms out while dragging?

**Comment by samhashemi** [comment]
Yup we're thinking the placement and moving would happen in a separate DOM-based layer that is fast and handles all interactions. Then, we want to translate that into a read-only set of MVT data that protomaps can render. 

I believe the limitation right now is that without something like `ignorePlacement`, we cannot explicit control which text gets rendered. We want to allow overlapping text in these kind of situations.

**Comment by bdon** [comment]
It's not totally clear to me yet what the advantage would be of ever displaying the annotations inside the basemap via protomaps.js, unless the goal is for the annotation labels to have mandatory text display that effectively "knocks out" underlying basemap labels. One way that could work is you do your annotation typing etc via DOM manipulation, and then a "commit" event happens where you inject a pseudo-label bounding box into the basemap that clears out that area for the annotation. This wouldn't be realtime, so the "commit" event could happen after the user is done typing or dragging the annotation.

**Comment by bdon** [comment]
We could use https://github.com/mapbox/geojson-vt to convert client-side annotation data into vector tiles for display in protomaps.js, but this seems like a roundabout design where the editing data structure is very different than the display data structure. Besides Leaflet, other reference points:

https://openseadragon.github.io/examples/ui-overlays/
iD editor on https://www.openstreetmap.org/edit (requires login)

**Comment by tarngerine** [comment]
> It's not totally clear to me yet what the advantage would be of ever displaying the annotations inside the basemap via protomaps.js

here are the primary constraints/goals we have which led us to considering this exploration

1. user-scalable and positionable text > unlike a "leafletmarker" which just repositions a div on the screen, we are syncing the scale in addition to position to the map zoom, and allowing users to further scale the text with some control
1. fractional zoom levels > we really want the map to feel smooth, with google maps online as a basis. so as you zoom, the text should scale with the map at the tiny fractional zoom levels. however, the way leaflet broadcasts its zoom and the way we do performant animations on our elements, it causes a "lag" where our elements are scaling slightly behind the zoom.
1. performance > we're using SVG text now and the performance drops precipitously, especially as you zoom in and the SVG gets very large and the browser is redrawing a ton of pixels. other alternatives we've tried to mixed results: using a textarea, div with content editable.

in 99% of the time we expect people to just be panning around and READING the map, vs the 1% time someone is EDITING text

the big theory behind this feature request is that canvas is more performant than SVG, as it can be more intelligent about which parts of text to draw, especially given tiling/zooming

we don't care about knocking out underlying basemap labels bc the way we style the text (colored, maybe stroked) and basemap (subdued) is already enough to make labels behind it a non-issue. instead of injecting a pseudo-label bounding box we'd rather just inject the text itself with its position and scale.

the API might look like this

```
function useTextTool() {
  function onCreate() {
    // start rendering DOM version to allow user to freely edit, scale adjust
    addElement({...})
  }

  function onSave() {
    // hide the DOM version of the label
    hideElement({...})

    // we call to protomaps to start rendering the text, it handles the positioning, tiling, zooming
    protomaps.addLabel({
      text: string,
      position: LatLngTuple,
      rotation: number, // deg
      baseZoomLevel: number, // the zoom level at which we created it
      scale: number, // further user adjusted scale on top of the baseZoomLevel, where the final scale is Math.pow(2, (baseZoomLevel - map.getZoom()) * scale)
    });
  }

  function onEdit() {
    // show the DOM editable version again and hide the protomaps version
    showElement({...}); 
    protomaps.hideLabel({id: element.id});
  }
}

```

does that make sense? are there any flawed assumptions in there? one that jumps out at me was your pushback

**Comment by bdon** [comment]
Yeah, that makes sense, but my approach would be to use a canvas element on top of the basemap, instead of working inside the basemap layer directly (right now implemented as a grid of Canvas squares). 

I think the internal mechanics of editable text will have way different demands than basemap Symbolizers so the code should be separate; you may want manual line breaking for annotations, or a11y; so the 1% SVG + 99% canvas case seems viable, the tricky parts may be to get visual parity across SVG + canvas across browsers.

For the lag you are seeing with animating elements, are you using the leaflet `zoomanim` event? Syncing animation to leaflet zoom might require you to reverse-engineer the CSS bezier transformation via https://github.com/mapbox/unitbezier , you'll also need to listen to the `move` event for property animating pinch on mobile.

**Comment by bdon** [comment]
To elaborate on another train of thought above, I think MVT tiling should be irrelevant to the annotation feature, unless there is multiple megabytes of annotation data. I would store the annotation data as a quad tree (probably https://github.com/mourner/rbush) so you can do windowed queries when panning/zooming

**Comment by tarngerine** [comment]
woof, i wish there was a fun youtube education person who did an r-tree
video...

**Comment by bdon** [comment]
examples of other "canvas + leaflet" approaches:
https://github.com/manubb/Leaflet.PixiOverlay - pretty good sync, because it compromises by transitioning the canvas with CSS + only resizing the canvas at the end of the animation
tangram: https://github.com/tangrams/tangram/blob/master/src/leaflet_layer.js#L387 works around this by replacing leaflet CSS transitions with javascript animations

In general, the syncing of the default leaflet transition to javascript is challenging (maybe impossible?) because CSS transitions happen off the main thread. worth investigating more, but this is a core motivation of why the WebGL mapping libraries (google maps GL version, mapboxGL) use GL all the way instead of letting the browser do compositing.
